INTERNAL: Revert "util: Drop the ENUM_PACKED macro"
This reverts commit 13f7ef5e0c01cb6f39ad3147800338f3d5b1f13e.

Build Error-:
src/gallium/auxiliary/util/u_prim.c:33:4: error: static assertion failed
due to requirement.

size of packed enum was coming 4 instead of 1 due to this change.

Tracked-On: OAM-106853
Signed-off-by: Ankit Agrawal <ankit.agarwal@intel.com>