gallium/radeon: fix missing winsys include in pipe-loader.
The commit 3b0b44f7def0acb4f7a7aef086c0bece321418a6 introduced a build
error:

error: dereferencing pointer to incomplete type

This patch fixes this issue in all the affected files.

Reviewed-by: Tom Stellard <thomas.stellard@amd.com>