vulkan/runtime: add spirv_info_h to vulkan_lite_runtime_header_gen_deps
spirv_info_h was added to idep_vulkan_lite_runtime_headers but it's also
needed for building libvulkan_lite_runtime.  Without this patch, from
a clean meson setup (tested with: -Dvulkan-drivers=freedreno -Dgallium-drivers= -Dplatforms=wayland)

ninja -C build src/vulkan/runtime/libvulkan_lite_runtime.a

In file included from ../src/vulkan/runtime/vk_physical_device.c:24:
../src/vulkan/runtime/vk_physical_device.h:32:10: fatal error: compiler/spirv/spirv_info.h: No such file or directory

Fixes: 1759c0eba77 ("vulkan: add helper to fill out spirv caps automatically")
Part-of: <https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/30189>
Change-Id: I07d89517fb6225634b6026d5458fde848c534561