anv: Add idep_genxml to dependencies of grl_genX_libs
Fix race condition when building ANV:

    In file included from src/intel/vulkan/grl/grl_metakernel_build_primref.c:40:
    ../src/intel/common/mi_builder.h:28:10: fatal error: 'genxml/genX_bits.h' file not found
    #include "genxml/genX_bits.h"

This change is already included in commit
41b2ed65e2532fd3be9ee7b74c74401169e81acd (genxml: generate opencl
packing headers) in the upstream.  Hence when updating mesa version,
this change can be safely removed.

Test-done: build mesa multiple times

Tracked-On: OAM-122542
Signed-off-by: Weifeng Liu <weifeng.liu@intel.com>