util: fix 32bit compiler error in fossilize_db
error: in call to 'fwrite', size * count is too large for the given buffer

sizeof(uint64_t) is used in the call to fwrite.

Part-of: <https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/30154>

Bug: 342026860
Test: build-fuchsia-turnip.sh
Change-Id: I2454c4bfa5afb028fe24b33a8e234dfab74ed666