INTERNAL: Fix compiling issues caused by meson build system
Issues including:

1. static declaration of **** follows non-static declaration for
   function timespec_get
2. ldd error: undefined symbol for functions major and minor
3. ffs and ffsll redefinition issue
4. ldd error: undefined symbol issue for functions build_id and futex
5. TLS symbol error: cannot load any more object with static TLS
6. Intel "Anvil" Vulkan driver requires the dl_iterate_phdr function
7. called object type 'uint32_t' is not a function or function pointer
8. duplicate defination of struct timespec. guarded with #ifndef.
9. fix error: 'backtrace/Backtrace.h' file not found.
10. fix ld.lld: error: version script assignment of 'global' to symbol
failed: symbol not defined.